CATEGORIES = [
    {
        "name": "Пуэр",
        "slug": "puer",
        "description": "Насыщенный чай для тех, кто ценит глубокий вкус, плотную текстуру и долгое спокойное послевкусие.",
        "image_url": "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 1,
    },
    {
        "name": "Улун",
        "slug": "oolong",
        "description": "Полуферментированный чай с цветочно-фруктовым ароматом, мягкой сладостью и многослойным вкусом.",
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 2,
    },
    {
        "name": "Зелёный чай",
        "slug": "green-tea",
        "description": "Свежий, прозрачный и бодрящий чай с травянистыми и ореховыми оттенками.",
        "image_url": "https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 3,
    },
    {
        "name": "Чёрный чай",
        "slug": "black-tea",
        "description": "Тёплый, насыщенный и уютный вкус на каждый день и для неспешных вечерних чаепитий.",
        "image_url": "https://images.unsplash.com/photo-1517701550927-30cf4ba1fdd8?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 4,
    },
    {
        "name": "Белый чай",
        "slug": "white-tea",
        "description": "Мягкий, тонкий и деликатный чай с лёгкой сладостью и тихой цветочной прозрачностью.",
        "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 5,
    },
    {
        "name": "Фруктовый чай",
        "slug": "fruit-tea",
        "description": "Яркие купажи с фруктами, ягодами и цветами для ароматных домашних ритуалов.",
        "image_url": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 6,
    },
    {
        "name": "Наборы",
        "slug": "gift-sets",
        "description": "Готовые решения для подарка, знакомства с китайским чаем и красивой домашней церемонии.",
        "image_url": "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 7,
    },
    {
        "name": "Посуда",
        "slug": "teaware",
        "description": "Чайники, пиалы и аксессуары для гунфу ча, которые делают подачу особенно красивой.",
        "image_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 8,
    },
    {
        "name": "Скидки",
        "slug": "sale",
        "description": "Избранные позиции с мягкой сезонной скидкой: удачный момент попробовать новое или собрать подарок.",
        "image_url": "https://images.unsplash.com/photo-1507914372368-b2b085b925a1?auto=format&fit=crop&w=1200&q=80",
        "sort_order": 9,
    },
]

PRODUCTS = [
    {
        "category_slug": "puer",
        "name": "Шу Пуэр блин 357 г",
        "slug": "shu-puer-cake-357",
        "short_description": "Плотный, древесный и очень согревающий пуэр для спокойных вечерних проливов.",
        "full_description": "Выдержанный шу пуэр с густым настоем цвета тёмного янтаря. Во вкусе читаются древесные, ореховые и шоколадные ноты, а в послевкусии остаётся мягкое ощущение тепла. Хорош для размеренного утра, долгой работы и тихих вечерних чайных пауз.",
        "price": "2490.00",
        "old_price": "2890.00",
        "image_url": "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 18,
        "is_featured": True,
    },
    {
        "category_slug": "puer",
        "name": "Шэн Пуэр весенний",
        "slug": "sheng-puer-spring",
        "short_description": "Живой и свежий шэн с травянистыми, медовыми и фруктовыми оттенками.",
        "full_description": "Молодой шэн пуэр для тех, кто любит чистую энергию зелёного листа и постепенное раскрытие вкуса в проливах. В аромате свежая трава, цветы и сухофрукты, во вкусе приятная терпкость и светлая сладость.",
        "price": "1890.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1523920290228-4f321a939b4c?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 14,
        "is_featured": False,
    },
    {
        "category_slug": "oolong",
        "name": "Те Гуань Инь",
        "slug": "tie-guan-yin",
        "short_description": "Цветочный улун с чистым ароматом сирени и мягкой сливочной текстурой.",
        "full_description": "Классический южнофуцзяньский улун с лёгкой обжаркой. Напиток раскрывается воздушным цветочным ароматом, нежной сладостью и чистым освежающим послевкусием. Подходит для спокойного дневного чаепития и знакомства с улунами.",
        "price": "1690.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 21,
        "is_featured": True,
    },
    {
        "category_slug": "oolong",
        "name": "Молочный улун",
        "slug": "milk-oolong",
        "short_description": "Мягкий улун с кремовым телом и деликатным сладким ароматом.",
        "full_description": "Комфортный и понятный чай с округлым вкусом, в котором сочетаются сливочные ноты, тёплая сладость и лёгкая карамельная мягкость. Отличный вариант для подарка и домашней чайной полки на каждый день.",
        "price": "1490.00",
        "old_price": "1790.00",
        "image_url": "https://images.unsplash.com/photo-1523906630133-f6934a1ab2b9?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 26,
        "is_featured": True,
    },
    {
        "category_slug": "oolong",
        "name": "Да Хун Пао",
        "slug": "da-hong-pao",
        "short_description": "Тёмный улун с жареными, минеральными и пряными нюансами.",
        "full_description": "Сложный и благородный улун из уишаньского стиля. В чашке слышны минералы, тёплый хлеб, какао и сухофрукты. Подходит тем, кто ищет насыщенный вкус и спокойную глубину без резкости.",
        "price": "2290.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1517701550927-30cf4ba1fdd8?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 12,
        "is_featured": False,
    },
    {
        "category_slug": "green-tea",
        "name": "Жасминовый зелёный чай",
        "slug": "jasmine-green-tea",
        "short_description": "Свежий зелёный чай с тонким жасминовым ароматом и чистым финишем.",
        "full_description": "Лёгкий и прозрачный напиток для тех, кто любит ясный вкус и деликатную цветочную ноту. Жасмин не перебивает чайную основу, а мягко поддерживает её, сохраняя свежесть и баланс.",
        "price": "1190.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 19,
        "is_featured": True,
    },
    {
        "category_slug": "green-tea",
        "name": "Лунцзин",
        "slug": "longjing",
        "short_description": "Знаменитый зелёный чай с ореховой сладостью и шелковистой текстурой.",
        "full_description": "Классический Лунцзин с ровным, тихим вкусом, где соединяются жареные каштаны, зелень и чуть сладковатое послевкусие. Хорош для утренних завариваний и тех моментов, когда нужен собранный, чистый тонус.",
        "price": "2390.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 9,
        "is_featured": False,
    },
    {
        "category_slug": "black-tea",
        "name": "Красный чай Дянь Хун",
        "slug": "dian-hong",
        "short_description": "Бархатистый красный чай с какао, медом и тёплой хлебной нотой.",
        "full_description": "Элегантный дяньхун с золотистыми типсами, плотным телом и мягкой сладостью. Вкус собранный, глубокий, без излишней терпкости. Идеален для уютного чаепития дома и красивого подарочного набора.",
        "price": "1590.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1517701550927-30cf4ba1fdd8?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 17,
        "is_featured": True,
    },
    {
        "category_slug": "black-tea",
        "name": "Лапсанг Сушонг",
        "slug": "lapsang-souchong",
        "short_description": "Дымный красный чай с характером, смолистыми и древесными оттенками.",
        "full_description": "Выразительный чай для тех, кто любит необычный профиль. Копчёный аромат напоминает костёр, хвойную смолу и сухое дерево, а во вкусе остаётся благородная согревающая глубина.",
        "price": "1790.00",
        "old_price": "1990.00",
        "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 8,
        "is_featured": False,
    },
    {
        "category_slug": "white-tea",
        "name": "Бай Му Дань",
        "slug": "bai-mu-dan",
        "short_description": "Мягкий белый чай с цветочно-медовым ароматом и прозрачным настоем.",
        "full_description": "Спокойный белый чай, в котором ощущаются полевые цветы, мёд и тонкая сладость сухофруктов. Хорош для медленных чаепитий и моментов, когда хочется тишины и лёгкости без лишней плотности.",
        "price": "2090.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 11,
        "is_featured": False,
    },
    {
        "category_slug": "white-tea",
        "name": "Серебряные иглы",
        "slug": "silver-needles",
        "short_description": "Тонкий белый чай с воздушным ароматом и деликатной сладостью.",
        "full_description": "Премиальный белый чай из нежных почек. Во вкусе почти нет грубости: только чистый светлый настой, шелковистая мягкость и аккуратное цветочное послевкусие. Идеален для знакомства с тихой эстетикой белых чаёв.",
        "price": "3290.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1507914372368-b2b085b925a1?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 6,
        "is_featured": True,
    },
    {
        "category_slug": "fruit-tea",
        "name": "Фруктовый чай с личи",
        "slug": "fruit-tea-lychee",
        "short_description": "Сочный купаж с личи, ягодами и лёгкой цветочной кислинкой.",
        "full_description": "Ароматный фруктовый сбор для тех, кто любит яркое настроение в чашке. Личи, ягоды и цветы соединяются в нежный сладко-кислый профиль, который приятно пить и горячим, и слегка охлаждённым.",
        "price": "990.00",
        "old_price": "1190.00",
        "image_url": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 23,
        "is_featured": True,
    },
    {
        "category_slug": "fruit-tea",
        "name": "Фруктовый чай манго-османтус",
        "slug": "fruit-tea-mango-osmanthus",
        "short_description": "Тропический купаж с манго, османтусом и мягкой медовой сладостью.",
        "full_description": "Тёплый, дружелюбный и очень ароматный купаж, который легко заваривать дома каждый день. Османтус добавляет утончённость, а манго и ягоды делают профиль округлым и солнечным.",
        "price": "1090.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 15,
        "is_featured": False,
    },
    {
        "category_slug": "gift-sets",
        "name": "Подарочный набор «Чайная церемония»",
        "slug": "gift-set-tea-ceremony",
        "short_description": "Элегантный набор для первого красивого знакомства с миром китайского чая.",
        "full_description": "Внутри собраны несколько популярных сортов, пиала и небольшая памятка по завариванию. Набор оформлен в спокойной премиальной стилистике и подойдёт для подарка, который хочется распаковывать медленно и с удовольствием.",
        "price": "4590.00",
        "old_price": "5290.00",
        "image_url": "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 7,
        "is_featured": True,
    },
    {
        "category_slug": "gift-sets",
        "name": "Подарочный бокс «Тихий вечер»",
        "slug": "gift-box-quiet-evening",
        "short_description": "Чайный бокс с мягкими сортами для расслабленного домашнего ритуала.",
        "full_description": "В коробке собраны улун, белый чай, сладкий фруктовый купаж и аксессуары для уютной подачи. Получается красивый подарок с понятным сценарием использования и действительно приятной атмосферой.",
        "price": "3890.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 10,
        "is_featured": False,
    },
    {
        "category_slug": "teaware",
        "name": "Чайник для гунфу ча",
        "slug": "gongfu-teapot",
        "short_description": "Компактный чайник для проливов с чистой формой и удобной посадкой в руке.",
        "full_description": "Удобный чайник для домашней церемонии, рассчитанный на короткие аккуратные проливы. Нейтральный дизайн хорошо сочетается с разной посудой, а форма делает его практичным для ежедневного использования.",
        "price": "2790.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 9,
        "is_featured": False,
    },
    {
        "category_slug": "teaware",
        "name": "Чайная пиала",
        "slug": "tea-cup-ceremony",
        "short_description": "Минималистичная пиала с тёплой глазурью для ежедневных чаепитий.",
        "full_description": "Небольшая пиала приятной формы, которая хорошо лежит в ладони и подчёркивает эстетику подачи. Подходит и для домашней полки, и как дополнение к подарочному набору.",
        "price": "790.00",
        "old_price": None,
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 34,
        "is_featured": True,
    },
    {
        "category_slug": "teaware",
        "name": "Набор для матча",
        "slug": "matcha-set",
        "short_description": "Набор аксессуаров для аккуратного приготовления матча дома.",
        "full_description": "В комплекте всё необходимое для спокойного домашнего ритуала: чаша, бамбуковый венчик и подставка. Подойдёт тем, кто любит японскую эстетику и хочет красиво интегрировать матча-паузу в свой день.",
        "price": "3190.00",
        "old_price": "3490.00",
        "image_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 5,
        "is_featured": False,
    },
    {
        "category_slug": "sale",
        "name": "Промо-набор «Знакомство с улунами»",
        "slug": "promo-oolong-selection",
        "short_description": "Три выразительных улуна в выгодном формате для первой дегустации.",
        "full_description": "Подборка из Те Гуань Инь, молочного улуна и Да Хун Пао в уменьшенных фасовках. Идеальный способ сравнить стили и выбрать любимое направление без большого чека.",
        "price": "2690.00",
        "old_price": "3290.00",
        "image_url": "https://images.unsplash.com/photo-1523906630133-f6934a1ab2b9?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 13,
        "is_featured": True,
    },
    {
        "category_slug": "sale",
        "name": "Подарочный бокс «Весеннее чаепитие»",
        "slug": "spring-tea-gift-box",
        "short_description": "Сезонный набор со скидкой для лёгких дневных чаепитий и подарков.",
        "full_description": "Внутри белый чай, зелёный жасминовый чай, фруктовый купаж и небольшая пиала. Получается светлый и очень подарочный набор, который легко показать клиенту уже на этапе MVP как готовый сезонный продукт.",
        "price": "3490.00",
        "old_price": "4190.00",
        "image_url": "https://images.unsplash.com/photo-1507914372368-b2b085b925a1?auto=format&fit=crop&w=1200&q=80",
        "stock_qty": 9,
        "is_featured": True,
    },
]

ADMIN_SETTINGS = [
    {"key": "shop_story", "value": "Мы подбираем китайский чай для спокойных домашних ритуалов, подарков и красивых повседневных пауз."},
    {"key": "pickup_address", "value": "Ташкент, ул. Чайная, 8"},
    {"key": "channel_cta", "value": "Следите за новинками и акциями в Telegram-канале магазина."},
    {"key": "payment_card_number", "value": "8600 1234 5678 9012"},
    {"key": "payment_card_holder", "value": "Golden Tea"},
    {"key": "payment_instruction", "value": "Переведите точную сумму заказа на карту, прикрепите скриншот чека и укажите удобный контакт для связи. После проверки администратор подтвердит заказ."},
    {"key": "payment_contact_hint", "value": "Укажите телефон или @telegram, чтобы менеджер мог быстро подтвердить оплату."},
]
